#!/usr/bin/env bash
#
# Install mechabar dependencies
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    August 22, 2025
# License: MIT

DEPS=(
	bluez-utils
	brightnessctl
	fzf
	libnotify
	networkmanager
	pacman-contrib
	waybar
)

RED=$'\e[31m'
GREEN=$'\e[32m'
BLUE=$'\e[34m'
RESET=$'\e[39m'

debug() { printf "%b" "$*" >&2; }

install() {
	local package
	for package in "$@"; do
		if pacman -Qi "$package" &>/dev/null; then
			debug "${GREEN}/${RESET} $package\n"
		else
			debug "\n${BLUE}*${RESET} $package...\n"

			if sudo pacman -S --noconfirm "$package"; then
				debug "\n${GREEN}+${RESET} $package\n"
			else
				debug "\n${RED}x${RESET} $package\n"
				((ERRORS += 1))
			fi
		fi
	done
}

main() {
	debug "${BLUE}Installing dependencies...${RESET}\n"

	install "${DEPS[@]}"

	debug '\nInstall "CommitMono Nerd Font" (otf-commit-mono-nerd)? [Y/n] '
	read -r

	case $REPLY in
		'' | [Yy])
			install otf-commit-mono-nerd
			;;
		*)
			cat <<-EOF

				| Different fonts render characters in different sizes,
				| which can affect the layout.
				| Import your preferred font file from ./styles/fonts/ to ./style.css.
			EOF
			;;
	esac

	debug "\n${BLUE}Restarting Waybar...${RESET}\n"

	if ! (systemctl --user is-enabled waybar.service &&
		systemctl --user restart waybar.service) &>/dev/null; then
		pkill waybar
		waybar &>/dev/null &
		disown
	fi

	if ((ERRORS > 0)); then
		debug "\nInstallation completed with ${RED}$ERRORS error(s)${RESET}\n"
	else
		debug "\n${GREEN}Installation complete!${RESET}\n"
	fi
}

main
