#!/usr/bin/env bash
#
# Connect to a Bluetooth device
#
# Requires bluez-utils (bluetoothctl) and fzf
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    August 19, 2025
# License: MIT

TIMEOUT=10

RED="\e[31m"
RESET="\e[39m"

usage() {
	cat <<-EOF
		USAGE: ${0##*/} [option]

		Connect to a Bluetooth device

		OPTIONS:
		  off       Power off Bluetooth
		  <none>    Power on Bluetooth and launch the CLI
	EOF
}

debug() {
	printf "%b" "$*" >&2
}

power_on() {
	state() {
		bluetoothctl show | awk '/PowerState/ {print $2}'
	}

	case $(state) in
		off)
			bluetoothctl power on >/dev/null
			;;
		off-blocked)
			rfkill unblock bluetooth

			local i
			for ((i = 1; i <= TIMEOUT; i++)); do
				debug "\rUnblocking Bluetooth... ($i/$TIMEOUT)"

				if [[ $(state) == on ]]; then
					break
				else
					sleep 1
				fi
			done

			if [[ $(state) != on ]]; then
				notify-send "Bluetooth" "Failed to unblock" -i "package-purge"
				exit 1
			fi
			;;
		*)
			return 0
			;;
	esac

	notify-send "Bluetooth On" -i "network-bluetooth-activated" \
		-h string:x-canonical-private-synchronous:bluetooth
}

list_devices() {
	bluetoothctl -t $TIMEOUT scan on >/dev/null &

	local num
	local i
	for ((i = 1; i <= TIMEOUT; i++)); do
		debug "\rScanning for devices... ($i/$TIMEOUT)"
		debug "\n${RED}Press [q] to stop${RESET}\n"

		num=$(bluetoothctl devices | grep -c "^Device")
		debug "\nDevices: $num"

		# move cursor 3 lines up
		debug "\e[3F"

		read -rsn 1 -t 1
		if [[ $REPLY == [Qq] ]]; then
			break
		fi
	done

	debug "\n${RED}Scanning stopped.${RESET}\n\n"

	LIST=$(bluetoothctl devices | sed "s/^Device //")

	if [[ -z $LIST ]]; then
		notify-send "Bluetooth" "No devices found" -i "package-broken"
		exit 1
	fi
}

select_device() {
	local header
	printf -v header "%-17s %s" "Address" "Name"

	local options=(
		"--border=sharp"
		"--border-label= Bluetooth Devices "
		"--cycle"
		"--ghost=Search"
		"--header=$header"
		"--height=~100%"
		"--highlight-line"
		"--info=inline-right"
		"--pointer="
		"--reverse"
	)

	ADDRESS=$(fzf "${options[@]}" <<<"$LIST" | awk '{print $1}')

	if [[ -z $ADDRESS ]]; then
		exit 1
	fi
}

connect_device() {
	local connected
	connected=$(bluetoothctl info "$ADDRESS" | awk '/Connected/ {print $2}')

	if [[ $connected == yes ]]; then
		notify-send "Bluetooth" "Already connected to this device" \
			-i "package-install"
		exit 1
	fi

	local paired
	paired=$(bluetoothctl info "$ADDRESS" | awk '/Paired/ {print $2}')

	if [[ $paired == no ]]; then
		debug "Pairing..."

		if ! timeout $TIMEOUT bluetoothctl pair "$ADDRESS" >/dev/null; then
			notify-send "Bluetooth" "Failed to pair" -i "package-purge"
			exit 1
		fi
	fi

	debug "\nConnecting..."

	if timeout $TIMEOUT bluetoothctl connect "$ADDRESS" >/dev/null; then
		notify-send "Bluetooth" "Successfully connected" -i "package-install"
	else
		notify-send "Bluetooth" "Failed to connect" -i "package-purge"
		exit 1
	fi
}

main() {
	case $1 in
		off)
			bluetoothctl power off
			notify-send 'Bluetooth Off' -i 'network-bluetooth-inactive' \
				-h string:x-canonical-private-synchronous:bluetooth
			return 0
			;;
		'')
			;;
		*)
			usage >&2
			return 1
			;;
	esac

	# make cursor invisible
	debug "\e[?25l"

	power_on
	list_devices

	# make cursor visible
	debug "\e[?25h"

	select_device
	connect_device
}

main "$@"
