#!/usr/bin/env bash
#
# Scan, select, and connect to Wi-Fi networks
#
# Switch off Wi-Fi:
#   $ network off
#
# Requires networkmanager (nmcli) and fzf
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    August 11, 2025
# License: MIT

TIMEOUT=5

RED="\e[31m"
RESET="\e[39m"

debug() {
	printf "%b" "$*" >&2
}

switch_on() {
	local state
	state=$(nmcli radio wifi)

	if [[ $state == enabled ]]; then
		return 0
	fi

	nmcli radio wifi on

	local new_state
	local i
	for ((i = 1; i <= TIMEOUT; i++)); do
		debug "\rEnabling Wi-Fi... ($i/$TIMEOUT)"

		new_state=$(nmcli -t -f STATE general)
		if [[ $new_state != "connected (local only)" ]]; then
			break
		fi

		sleep 1
	done

	notify-send "Wi-Fi Enabled" -i "network-wireless-on" \
		-h string:x-canonical-private-synchronous:network
}

get_networks() {
	nmcli device wifi rescan

	local i
	for ((i = 1; i <= TIMEOUT; i++)); do
		debug "\rScanning for networks... ($i/$TIMEOUT)"

		LIST=$(timeout 1 nmcli device wifi list)

		NETWORKS=$(tail -n +2 <<<"$LIST" | awk '$2 != "--"')
		if [[ -n $NETWORKS ]]; then
			break
		fi
	done

	debug "\n${RED}Scanning stopped.${RESET}\n\n"

	if [[ -z $NETWORKS ]]; then
		notify-send "Wi-Fi" "No networks found" -i "package-broken"
		exit 1
	fi
}

select_network() {
	local header
	header=$(head -n 1 <<<"$LIST")

	local options=(
		"--border=sharp"
		"--border-label= Wi-Fi Networks "
		"--cycle"
		"--ghost=Search"
		"--header=$header"
		"--height=~100%"
		"--highlight-line"
		"--info=inline-right"
		"--pointer="
		"--reverse"
	)

	BSSID=$(fzf "${options[@]}" <<<"$NETWORKS" | awk '{print $1}')

	case $BSSID in
		'')
			exit 1
			;;
		'*')
			notify-send "Wi-Fi" "Already connected to this network" \
				-i "package-install"
			exit 1
			;;
	esac
}

connect() {
	debug "Connecting...\n"

	if nmcli -a device wifi connect "$BSSID"; then
		notify-send "Wi-Fi" "Successfully connected" -i "package-install"
	else
		notify-send "Wi-Fi" "Failed to connect" -i "package-purge"
		exit 1
	fi
}

main() {
	if [[ $1 == off ]]; then
		nmcli radio wifi off
		notify-send 'Wi-Fi Disabled' -i 'network-wireless-off' \
			-h string:x-canonical-private-synchronous:network
		exit 0
	fi

	# make cursor invisible
	debug "\e[?25l"

	switch_on
	get_networks

	# make cursor visible
	debug "\e[?25h"

	select_network
	connect
}

main "$@"
