#!/usr/bin/env bash
#
# Execute a terminal emulator
#
# Original script:
#   https://github.com/davatorium/rofi/blob/next/script/rofi-sensible-terminal
#
# Authors: Han Boetes     <han@mijncomputer.nl>
#          Dave Davenport <qball@gmpclient.org>
#          Jesse Mirabel  <sejjymvm@gmail.com>
# Date:    July 22, 2026
# License: MIT

# shellcheck disable=2153
for terminal in $TERMINAL alacritty aterm Eterm foot ghostty kitty konsole \
	lxterminal mate-terminal qterminal roxterm rxvt st terminology urxvt   \
	uxterm wezterm x-terminal-emulator xfce4-terminal.wrapper xterm
do
	if command -v "$terminal" &>/dev/null; then
		exec $terminal "$@"
	fi
done

notify-send "Failed to find a suitable terminal" -i "package-purge"
