#!/usr/bin/env bash
#
# Update Arch packages
#
# Requires pacman-contrib (checkupdates)
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    August 16, 2025
# License: MIT

TIMEOUT=10

GREEN="\e[32m"
BLUE="\e[34m"
RESET="\e[39m"

usage() {
	cat <<-EOF
		USAGE: ${0##*/} [option]

		Update Arch packages

		OPTIONS:
		  module    Print Waybar-compatible JSON output
		  <none>    Launch the CLI
	EOF
}

debug() {
	printf "%b\n" "$*" >&2
}

detect_helper() {
	local helper
	for helper in aura pakku paru pikaur trizen yay; do
		if command -v "$helper" >/dev/null; then
			HELPER=$helper
			break
		fi
	done
}

check_updates() {
	FAILED=false

	local packages status
	packages=$(timeout $TIMEOUT checkupdates)
	status=$?

	if ((status != 0 && status != 2)); then
		FAILED=true
		UPDATES=0
		return 1
	else
		UPDATES=$(grep -c . <<<"$packages")
	fi

	detect_helper

	if [[ -n $HELPER ]]; then
		local aur_packages aur_status
		aur_packages=$(timeout "$TIMEOUT" "$HELPER" -Qua)
		aur_status=$?

		if ((${#aur_packages} > 0 && aur_status != 0)); then
			FAILED=true
			AUR_UPDATES=0
			return 1
		else
			# Filter out ignored AUR packages
			aur_packages=$(awk '!/\[ignored\]/ {print $1}' <<<"$aur_packages")
			AUR_UPDATES=$(grep -c . <<<"$aur_packages")
		fi
	fi
}

update_packages() {
	debug "${BLUE}Updating packages...${RESET}"

	if [[ -n $HELPER ]]; then
		command $HELPER -Syu
	else
		sudo pacman -Syu
	fi

	notify-send "Update Complete" -i "package-install"

	debug "\n${GREEN}Update complete!${RESET}"
	read -rsn 1 -p "Press any key to exit..."
}

print_module() {
	local icon tooltip

	if $FAILED; then
		icon='󰒑'
		tooltip="<b>Failed to fetch updates</b>\nRight-click to retry"
	elif ((UPDATES + AUR_UPDATES == 0)); then
		icon='󰸟'
		tooltip="No updates available"
	else
		icon='󰄠'
		tooltip="<b>Pacman</b>: $UPDATES"

		if [[ -n $HELPER ]]; then
			local padding
			printf -v padding "%*s" $((6 - ${#HELPER})) ''

			tooltip+="\n<b>${HELPER^}</b>: $padding$AUR_UPDATES"
		fi
	fi

	cat <<-EOF
		{ "text": "$icon", "tooltip": "$tooltip" }
	EOF
}

main() {
	case $1 in
		module)
			check_updates
			print_module
			;;
		'')
			trap "pkill -RTMIN+1 waybar" EXIT # Update the module on exit

			update_packages
			;;
		*)
			usage >&2
			return 1
			;;
	esac
}

main "$@"
